### ISSUE TITLE
CSV parsing error should be user error

### ISSUE THREAD

**Issue by Halama** [keboola/dynamodb-extractor#16]
Columns `properties,file_data,notes` were JSON data and [Force Type](https://developers.keboola.com/extend/generic-extractor/configuration/config/mappings/#mapping-without-processing) wasn't set it mapping.

```
 Application error: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-dynamodb:v0.6.0 container '457607564-457607565--0-keboola-ex-dynamodb' failed: (2) [2018-10-23 13:51:00] app-errors.ERROR: Error writing 'properties,file_data,notes' column: Cannot write object into a column {"trace":"#0 /code/src/Keboola/DynamoDbExtractor/Parser.php(51): Keboola\\CsvMap\\Mapper->parse(Array)\n#1 /code/src/Keboola/DynamoDbExtractor/Extractor.php(81): Keboola\\DynamoDbExtractor\\Parser->parseAndWriteCsvFiles()\n#2 /code/src/Keboola/DynamoDbExtractor/RunCommand.php(57): Keboola\\DynamoDbExtractor\\Extractor->actionRun('/data/out/table...')\n#3 /code/vendor/symfony/console/Command/Command.php(252): Keboola\\DynamoDbExtractor\\RunCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#4 /code/vendor/symfony/console/Application.php(865): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#5 /code/vendor/symfony/console/Application.php(241): Symfony\\Component\\Console\\Application->doRunCommand(Object(Keboola\\DynamoDbExtractor\\RunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#6 /code/vendor/symfony/console/Application.php(143): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 /code/src/app.php(12): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 {main}"} []
```

Reference https://keboola.zendesk.com/agent/tickets/9347

**Comment by ujovlado** [comment]
Toto bude easy myslim, len sa prida dalsia exception sem:

https://github.com/keboola/dynamodb-extractor/blob/8cacf3db2ffdd38c9d9f7cd8a90940b4fa29bb77/src/Keboola/DynamoDbExtractor/RunCommand.php#L64
